version: '3.8'

services:
  landing:
    image: focus_landing:latest
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.landing.rule=Host(`focus-business.com`)"
        - "traefik.http.routers.landing.entrypoints=websecure"
        - "traefik.http.routers.landing.tls.certresolver=myresolver"
        - "traefik.http.services.landing.loadbalancer.server.port=80"
    networks:
      - app-network

networks:
  app-network:
    external: true
    driver: overlay