version: '3.8'

services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    image: focus-landing:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 16M
          cpus: '1.5'